FROM ubuntu:latest
# Download the installer script:
# Alternatively: wget --secure-protocol=TLSv1_2 --https-only https://get.opentofu.org/install-opentofu.sh -O install-opentofu.sh
# Give it execution permissions:
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PIPENV_VENV_IN_PROJECT=1
ENV PIPENV_IGNORE_VIRTUALENVS=1

# install packages
RUN set -eux \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        curl \
        git \
        libgl1 \
        libglib2.0-0 \
        unixodbc-dev \
        openssh-client \
        python3 \
        python3-pip \
        python3-tk \
        python3-venv \
    && curl -sSL -O https://packages.microsoft.com/config/ubuntu/$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2)/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools18 \
    && apt-get install -y unixodbc-dev \
    && python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && /opt/venv/bin/pip install pipenv \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y telnet-ssl
RUN curl --proto 'https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh \
    && chmod +x install-opentofu.sh \
    && ./install-opentofu.sh --install-method deb


# Azure

RUN mkdir -p /etc/apt/keyrings \
    && apt-get update \
    && apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y \
    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/keyrings/microsoft.gpg > /dev/null \
    && AZ_REPO=$(lsb_release -cs) \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list \
    && apt-get update && apt-get install azure-cli -y

RUN apt-get install -y docker.io sudo

# Add jq for CICD work
RUN apt-get install -y jq

RUN groupadd -f docker && \
    usermod -aG docker ubuntu && \
    echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers



USER ubuntu